//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessoSeletivo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Label {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Label() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProcessoSeletivo.Resources.Label", typeof(Label).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pronto, concluído! Agradecemos o cadastro!.
        /// </summary>
        public static string AgradecimentoPeloCadastro {
            get {
                return ResourceManager.GetString("AgradecimentoPeloCadastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precisamos que você responda algumas perguntas para que possamos saber qual é o seu perfil técnico. Coisa rápida, não se preocupe..
        /// </summary>
        public static string DescricaoDoCadastro {
            get {
                return ResourceManager.GetString("DescricaoDoCadastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desenvolvimento Android.
        /// </summary>
        public static string DesenvolvimentoAndroid {
            get {
                return ResourceManager.GetString("DesenvolvimentoAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desenvolvimento iOS.
        /// </summary>
        public static string DesenvolvimentoIOS {
            get {
                return ResourceManager.GetString("DesenvolvimentoIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agora, precisamos que você avalie suas habilidades nos itens abaixo, classificando como 0 (whaaaaat ?) até 10 (Chuck Norris)..
        /// </summary>
        public static string InstrucoesParaAvaliacaoConhecimentos {
            get {
                return ResourceManager.GetString("InstrucoesParaAvaliacaoConhecimentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha seus dados nos campos abaixo:.
        /// </summary>
        public static string InstrucoesParaDadosBasicos {
            get {
                return ResourceManager.GetString("InstrucoesParaDadosBasicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://meuspedidos.com.br/.
        /// </summary>
        public static string LinkSiteDaEmpresa {
            get {
                return ResourceManager.GetString("LinkSiteDaEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Que a força seja com você!.
        /// </summary>
        public static string SaudacaoAposDescricaoDoCadastro {
            get {
                return ResourceManager.GetString("SaudacaoAposDescricaoDoCadastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olá, seja bem vindo(a) ao cadastro para seleção de colaboradores!.
        /// </summary>
        public static string SaudacaoPagina {
            get {
                return ResourceManager.GetString("SaudacaoPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleção de colaboradores.
        /// </summary>
        public static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
    }
}
