//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessoSeletivo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProcessoSeletivo.Resources.Mensagem", typeof(Mensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigado por se candidatar.
        /// </summary>
        public static string AssuntoEmail {
            get {
                return ResourceManager.GetString("AssuntoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envio efetuado com sucesso!.
        /// </summary>
        public static string CadastroEnviadoComSucesso {
            get {
                return ResourceManager.GetString("CadastroEnviadoComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor preencher o e-mail..
        /// </summary>
        public static string CampoObrigatorioEmail {
            get {
                return ResourceManager.GetString("CampoObrigatorioEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor preencher o nome..
        /// </summary>
        public static string CampoObrigatorioNome {
            get {
                return ResourceManager.GetString("CampoObrigatorioNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigado por se candidatar, assim que tivermos uma vaga disponível para programador Back-End entraremos em contato..
        /// </summary>
        public static string CorpoEmailBackEnd {
            get {
                return ResourceManager.GetString("CorpoEmailBackEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigado por se candidatar, assim que tivermos uma vaga disponível para programador Front-End entraremos em contato..
        /// </summary>
        public static string CorpoEmailFrontEnd {
            get {
                return ResourceManager.GetString("CorpoEmailFrontEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigado por se candidatar, assim que tivermos uma vaga disponível para programador entraremos em contato..
        /// </summary>
        public static string CorpoEmailGenerico {
            get {
                return ResourceManager.GetString("CorpoEmailGenerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigado por se candidatar, assim que tivermos uma vaga disponível para programador Mobile entraremos em contato..
        /// </summary>
        public static string CorpoEmailMobile {
            get {
                return ResourceManager.GetString("CorpoEmailMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor informar o e-mail completo, incluindo o @provedor...
        /// </summary>
        public static string EmailInvalido {
            get {
                return ResourceManager.GetString("EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao enviar.
        /// </summary>
        public static string ErroAoEnviar {
            get {
                return ResourceManager.GetString("ErroAoEnviar", resourceCulture);
            }
        }
    }
}
